### ISSUE TITLE
Improve the error message of Config.check()

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-core#462]
**Description**

When config a SQLDataNode without required properties, the Config checker works correctly. 

However, the message is kinda long. It can be improved for better readability.

For example,

```python
y_cfg = Config.configure_data_node(id="y", storage_type="sql")
```

will output several error when running the Core service

```
[2023-02-03 09:37:39,172][Taipy][INFO] Issue(level='INFO', field='comparators', value=defaultdict(<class 'list'>, {}), message='No scenario comparators defined for scenario my_scenario', tag='_ScenarioConfigChecker')
[2023-02-03 09:37:39,172][Taipy][ERROR] Issue(level='ERROR', field='properties', value='db_username', message='`y` DataNode is missing the required property `db_username` for type `sql`', tag='_DataNodeConfigChecker')
[2023-02-03 09:37:39,172][Taipy][ERROR] Issue(level='ERROR', field='properties', value='db_password', message='`y` DataNode is missing the required property `db_password` for type `sql`', tag='_DataNodeConfigChecker')
[2023-02-03 09:37:39,172][Taipy][ERROR] Issue(level='ERROR', field='properties', value='db_name', message='`y` DataNode is missing the required property `db_name` for type `sql`', tag='_DataNodeConfigChecker')
[2023-02-03 09:37:39,172][Taipy][ERROR] Issue(level='ERROR', field='properties', value='db_engine', message='`y` DataNode is missing the required property `db_engine` for type `sql`', tag='_DataNodeConfigChecker')
[2023-02-03 09:37:39,172][Taipy][ERROR] Issue(level='ERROR', field='properties', value='read_query', message='`y` DataNode is missing the required property `read_query` for type `sql`', tag='_DataNodeConfigChecker')
[2023-02-03 09:37:39,172][Taipy][ERROR] Issue(level='ERROR', field='properties', value='write_query_builder', message='`y` DataNode is missing the required property `write_query_builder` for type `sql`', tag='_DataNodeConfigChecker')
Traceback (most recent call last):
  File "/Users/trgiangdo/Developer/test/test_migration.py", line 17, in <module>
    tp.Core().run()
  File "/Users/trgiangdo/.local/share/virtualenvs/test-ANcl6Zy-/lib/python3.10/site-packages/taipy/core/_core.py", line 49, in run
    self.__check_config()
  File "/Users/trgiangdo/.local/share/virtualenvs/test-ANcl6Zy-/lib/python3.10/site-packages/taipy/core/_core.py", line 66, in __check_config
    Config.check()
  File "/Users/trgiangdo/.local/share/virtualenvs/test-ANcl6Zy-/lib/python3.10/site-packages/taipy/config/config.py", line 178, in check
    cls.__log_message(cls)
  File "/Users/trgiangdo/.local/share/virtualenvs/test-ANcl6Zy-/lib/python3.10/site-packages/taipy/config/config.py", line 250, in __log_message
    raise ConfigurationIssueError("Configuration issues found.")
taipy.config.exceptions.exceptions.ConfigurationIssueError: Configuration issues found.
```

**Expected behavior**

The error message can be shorter, and no Exception raise at the end. For example:
```
[2023-02-03 09:37:39,172][Taipy][INFO] No scenario comparators defined for scenario my_scenario
[2023-02-03 09:37:39,172][Taipy][ERROR] `y` DataNode is missing the required property `db_username` for type `sql`
[2023-02-03 09:37:39,172][Taipy][ERROR] `y` DataNode is missing the required property `db_password` for type `sql`
[2023-02-03 09:37:39,172][Taipy][ERROR] `y` DataNode is missing the required property `db_name` for type `sql`
[2023-02-03 09:37:39,172][Taipy][ERROR] `y` DataNode is missing the required property `db_engine` for type `sql`
[2023-02-03 09:37:39,172][Taipy][ERROR] `y` DataNode is missing the required property `read_query` for type `sql`
[2023-02-03 09:37:39,172][Taipy][ERROR] `y` DataNode is missing the required property `write_query_builder` for type `sql`
```

**Comment by jrobinAV** [comment]
I believe it is more generic than just SQLDataNode checkers.
It is the way we display issues in the logs. No?

in config.py::__log_messages we display str(issue) instead of displaying issue.message

The ticket should be moved to taipy-config repo. Am I right?

**Comment by trgiangdo** [comment]
Right, let me check again and I will move the ticket.
